from pathlib import Path

from ai.dictation_plan import DictationPlanBuilder


validated_data = {
    "original_text": (
        "Вчера утром я проснулся раньше обычного, потому что у меня "
        "была важная встреча на работе. Я быстро позавтракал, проверил "
        "электронную почту и вышел из дома около восьми часов. Погода "
        "была холодная и дождливая, поэтому я решил поехать на автобусе "
        "вместо того, чтобы идти пешком. Когда я приехал в офис, "
        "обнаружил, что встреча отменена."
    ),

    "chunks": [
        {
            "text": "Вчера утром я проснулся раньше обычного,",
            "ends_sentence": False,
        },
        {
            "text": "потому что у меня была важная встреча на работе.",
            "ends_sentence": True,
        },
        {
            "text": "Я быстро позавтракал, проверил электронную почту",
            "ends_sentence": False,
        },
        {
            "text": "и вышел из дома около восьми часов.",
            "ends_sentence": True,
        },
        {
            "text": "Погода была холодная и дождливая,",
            "ends_sentence": False,
        },
        {
            "text": "поэтому я решил поехать на автобусе",
            "ends_sentence": False,
        },
        {
            "text": "вместо того, чтобы идти пешком.",
            "ends_sentence": True,
        },
        {
            "text": (
                "Когда я приехал в офис, обнаружил, "
                "что встреча отменена."
            ),
            "ends_sentence": True,
        },
    ],

    "total_chunks": 8,
}


def test_dictation_plan():

    builder = DictationPlanBuilder(
        phrase_code="ru",
        phrase_locale="ru-RU",
        phrase_voice="ru-RU-SvetlanaNeural",

        speed=1.0,
        repeat_count=1,

        pause_factor=2.0,
        pause_min=300,
        pause_max=10000,

        set_name="Dictation Test",
        set_description="Generated by OpenAI",
    )

    data = builder.build(validated_data)

    print()
    print("Dictation plan")
    print("-" * 80)

    print(
        f"Items: {data['set']['items_count']}"
    )

    for item in data["items"]:

        print(
            f"{item['item_order']:2}. "
            f"{item['pause_ms']:5} ms | "
            f"{item['phrase_text']}"
        )

    output_file = (
        Path(__file__).parent
        / "plan_session.json"
    )

    builder.save(
        data,
        output_file
    )

    print()
    print(f"Saved: {output_file}")


if __name__ == "__main__":
    test_dictation_plan()